temp: Skip tests and PyPI

diff --git a/.github/workflows/pypi.yaml b/.github/workflows/pypi.yaml
--- a/.github/workflows/pypi.yaml
+++ b/.github/workflows/pypi.yaml
@@ -46,21 +46,21 @@ jobs:
         poetry config virtualenvs.create false --local
         poetry install
 
-    - name: Run tests
-      run: |
-        ./runtests.sh | tee output.txt
-        if grep -q "= FAILURES =" output.txt; then
-          echo "Tests failed"
-          exit 1
-        fi
+    # - name: Run tests
+    #   run: |
+    #     ./runtests.sh | tee output.txt
+    #     if grep -q "= FAILURES =" output.txt; then
+    #       echo "Tests failed"
+    #       exit 1
+    #     fi
 
     - name: Build distribution
       run: python3 -m poetry build
 
-    - name: Publish distribution to PyPI
-      uses: pypa/gh-action-pypi-publish@release/v1
-      with:
-        password: ${{ secrets.PYPI_API_TOKEN }}
+    # - name: Publish distribution to PyPI
+    #   uses: pypa/gh-action-pypi-publish@release/v1
+    #   with:
+    #     password: ${{ secrets.PYPI_API_TOKEN }}
 
     - name: Create GitHub Release
       id: create_release
